apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-crawler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-crawler
  template:
    metadata:
      labels:
        app: news-crawler
    spec:
      containers:
        - name: news-crawler-container
          image: news-crawler:latest
          ports:
            - containerPort: 18080

---
apiVersion: v1
kind: Service
metadata:
  name: news-crawler-service
spec:
  type: NodePort
  selector:
    app: news-crawler
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
      nodePort: 30000