application:
  timezone: UTC
  locale: en

app:
  host:
    naver: https://openapi.naver.com/v1/search/news.json

spring:
  application:
    name: news-crawler
  web:
    locale: en

  jpa:
    hibernate:
      ddl-auto: none
  http:
    multipart:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    news:
      name: NEWS-CRAWLER
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.219.116:3306/news_crawler?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&cacheCallableStmts=true&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
      username: news_crawler
      password: news_crawler
      #      driver-class-name: software.aws.rds.jdbc.mysql.Driver
      #      jdbc-url :
      #      username:
      #      password:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 5

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
debug: false
logging:
  level:
    root: debug

