application:
  timezone: UTC
  locale: en


spring:
  application:
    name: news-crawler
  web:
    locale: en

  jpa:
    hibernate:
      ddl-auto: none
  http:
    multipart:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_test
    password: 0000
    connection-test-query: SELECT 1
    minimum-idle: 5
    maximum-pool-size: 5
    url: jdbc:mysql://192.168.219.116:3306
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

debug: false